import { PrismaClient } from "../src/generated/prisma";

const prisma = new PrismaClient();

const patterns = [
  // === BASICS (10) ===
  {
    name: "Sugar Push",
    slug: "sugar-push",
    beats: 6,
    difficulty: "beginner",
    category: "basics",
    description: "The foundational 6-count pattern. Leader pushes follower away, follower walks forward and anchors.",
    mechanics: JSON.stringify(["1: Leader steps back left, follower steps forward right", "2: Leader steps back right, follower steps forward left", "3&4: Leader triple steps in place, follower walks forward and begins anchor", "5&6: Both anchor in place — triple step with stretch and compression"]),
    commonMistakes: JSON.stringify(["Follower not walking through the slot", "Leader not creating clear compression on 1-2", "Rushing the anchor — not letting the stretch develop", "Leader backing up too far instead of just weighting back"]),
  },
  {
    name: "Left Side Pass",
    slug: "left-side-pass",
    beats: 6,
    difficulty: "beginner",
    category: "basics",
    description: "Follower passes leader on the left side through the slot. Foundation for many variations.",
    mechanics: JSON.stringify(["1: Leader steps back left, initiates lead for follower to pass", "2: Leader steps right, clearing the slot", "3&4: Leader triple steps to end of slot, follower walks through", "5&6: Both anchor — follower now at opposite end of slot"]),
    commonMistakes: JSON.stringify(["Leader not clearing the slot early enough", "Follower not walking in a straight line through the slot", "Lost connection during the pass", "Not maintaining frame while passing"]),
  },
  {
    name: "Right Side Pass",
    slug: "right-side-pass",
    beats: 6,
    difficulty: "beginner",
    category: "basics",
    description: "Follower passes leader on the right side. Often used as a starter or reset pattern.",
    mechanics: JSON.stringify(["1: Leader steps back left, leads follower to right side", "2: Leader steps right, clearing the slot", "3&4: Leader triple steps in place, follower walks through slot", "5&6: Both anchor in place"]),
    commonMistakes: JSON.stringify(["Confusing with left side pass hand positions", "Leader not creating clear directional lead", "Follower over-rotating", "Anchor feels disconnected from the pass"]),
  },
  {
    name: "Sugar Tuck",
    slug: "sugar-tuck",
    beats: 6,
    difficulty: "beginner",
    category: "basics",
    description: "A tuck turn variation of the sugar push. Follower turns under the arm after the push.",
    mechanics: JSON.stringify(["1: Leader steps back, creating compression", "2: Leader redirects follower for the turn", "3&4: Follower executes inside turn, leader triple steps", "5&6: Both anchor — reestablish connection"]),
    commonMistakes: JSON.stringify(["Leader forcing the turn with the arm", "Follower anticipating the turn before the lead", "Lost connection after the tuck", "Not completing the turn before the anchor"]),
  },
  {
    name: "Starter Step",
    slug: "starter-step",
    beats: 8,
    difficulty: "beginner",
    category: "basics",
    description: "The standard way to begin social dancing. Two walks and a triple step to establish connection.",
    mechanics: JSON.stringify(["1-2: Walk walk, establishing rhythm and connection", "3&4: Triple step together", "5-6: Walk walk", "7&8: Triple step, settle into slot"]),
    commonMistakes: JSON.stringify(["Starting without establishing connection first", "Moving too quickly into the first pattern", "Not matching partner's energy level", "Forgetting to breathe and settle into the music"]),
  },
  {
    name: "Push Break",
    slug: "push-break",
    beats: 6,
    difficulty: "beginner",
    category: "basics",
    description: "Leader pushes follower out and brings them back. Builds understanding of compression and leverage.",
    mechanics: JSON.stringify(["1-2: Both walk together with compression", "3&4: Push out — leader extends, follower stretches away", "5&6: Both anchor — follower at full stretch"]),
    commonMistakes: JSON.stringify(["Using arms instead of body for the push", "Not maintaining connection during the extension", "Follower not matching the energy of the push", "Anchor without real stretch"]),
  },
  {
    name: "Underarm Pass",
    slug: "underarm-pass",
    beats: 6,
    difficulty: "beginner",
    category: "basics",
    description: "Basic underarm turn where follower passes under leader's raised arm through the slot.",
    mechanics: JSON.stringify(["1: Leader steps back, raises lead hand", "2: Leader steps aside, follower begins to pass", "3&4: Follower walks under arm through the slot", "5&6: Both anchor, reconnect"]),
    commonMistakes: JSON.stringify(["Leader lifting arm too high or too low", "Follower ducking under the arm", "Lost frame during the pass", "Not re-establishing connection at the anchor"]),
  },
  {
    name: "Basic Whip",
    slug: "basic-whip",
    beats: 8,
    difficulty: "beginner",
    category: "basics",
    description: "The foundational 8-count pattern. Follower comes toward leader, redirects, and returns down the slot.",
    mechanics: JSON.stringify(["1-2: Follower walks toward leader (walk walk)", "3&4: Leader redirects follower with body movement (triple step)", "5-6: Follower walks back down the slot (walk walk)", "7&8: Both anchor (triple step) — stretch at end of slot"]),
    commonMistakes: JSON.stringify(["Leader using arm instead of body to redirect", "Follower not committing to walking toward leader", "Missing the redirection timing on 3", "Not getting to the end of the slot for the anchor"]),
  },
  {
    name: "Tuck Turn",
    slug: "tuck-turn",
    beats: 6,
    difficulty: "beginner",
    category: "basics",
    description: "An inside turn led from a tuck (quick compression-release). One of the most common turns in WCS.",
    mechanics: JSON.stringify(["1: Leader creates compression by stepping back", "2: Leader redirects — tucks follower for the turn", "3&4: Follower executes inside turn, leader triple steps", "5&6: Both anchor — reestablish stretch"]),
    commonMistakes: JSON.stringify(["Winding up with the arm instead of body", "Follower spinning instead of turning with control", "Leader pulling follower off balance during tuck", "Not settling into the anchor after the turn"]),
  },
  {
    name: "Change of Places",
    slug: "change-of-places",
    beats: 6,
    difficulty: "beginner",
    category: "basics",
    description: "Leader and follower swap ends of the slot. Both travel through each other's position.",
    mechanics: JSON.stringify(["1: Leader steps back, begins to open slot", "2: Both begin passing each other", "3&4: Leader and follower pass each other in the slot", "5&6: Both anchor at opposite ends"]),
    commonMistakes: JSON.stringify(["Collision in the middle of the slot", "Not committing to the full slot change", "Losing connection during the pass", "Anchor at wrong end of slot"]),
  },

  // === PUSH/PULL (10) ===
  {
    name: "Inside Roll",
    slug: "inside-roll",
    beats: 6,
    difficulty: "intermediate",
    category: "push-pull",
    description: "Follower rolls inward (toward the lead arm) through the slot. Creates a smooth, flowing movement.",
    mechanics: JSON.stringify(["1: Leader steps back, initiates inward lead", "2: Leader guides follower into inward rotation", "3&4: Follower rolls inward through the slot", "5&6: Both anchor with reconnection"]),
    commonMistakes: JSON.stringify(["Rolling too tight — not traveling through the slot", "Leader over-rotating the follower", "Follower losing balance during the roll", "Not maintaining stretch at the anchor"]),
  },
  {
    name: "Outside Roll",
    slug: "outside-roll",
    beats: 6,
    difficulty: "intermediate",
    category: "push-pull",
    description: "Follower rolls outward (away from lead arm) through the slot. Complementary to the inside roll.",
    mechanics: JSON.stringify(["1: Leader steps back, initiates outward lead", "2: Leader guides follower into outward rotation", "3&4: Follower rolls outward through the slot", "5&6: Both anchor — reestablish connection"]),
    commonMistakes: JSON.stringify(["Follower not trusting the outward direction", "Leader giving unclear rotational lead", "Too much arm, not enough body", "Finishing with back to partner"]),
  },
  {
    name: "Shoulder Check",
    slug: "shoulder-check",
    beats: 6,
    difficulty: "intermediate",
    category: "push-pull",
    description: "Leader redirects follower using shoulder/body connection. A compact, sharp pattern.",
    mechanics: JSON.stringify(["1-2: Follower walks toward leader", "3: Leader redirects with body (shoulder catch)", "4: Follower responds to the redirection", "5&6: Both anchor with stretch"]),
    commonMistakes: JSON.stringify(["Using hand/arm instead of body for the check", "Too aggressive — should be a redirect, not a block", "Follower not walking through with commitment", "Missing the timing of the check"]),
  },
  {
    name: "Push & Spin",
    slug: "push-and-spin",
    beats: 6,
    difficulty: "intermediate",
    category: "push-pull",
    description: "From compression, leader pushes follower into a free spin. Tests follower's balance and spotting.",
    mechanics: JSON.stringify(["1-2: Build compression together", "3: Leader pushes from the body, releases follower", "4: Follower executes free spin", "5&6: Both anchor — follower catches connection"]),
    commonMistakes: JSON.stringify(["Follower not using the push energy for the spin", "Leader pushing off-axis", "Follower over-spinning or under-spinning", "Not catching the connection cleanly at the anchor"]),
  },
  {
    name: "Basket Whip",
    slug: "basket-whip",
    beats: 8,
    difficulty: "intermediate",
    category: "push-pull",
    description: "8-count whip where leader wraps follower into a basket hold at the redirection point.",
    mechanics: JSON.stringify(["1-2: Follower walks toward leader", "3&4: Leader wraps follower into crossed-arm (basket) hold", "5-6: Follower walks back down slot in basket hold", "7&8: Leader unwraps follower, both anchor"]),
    commonMistakes: JSON.stringify(["Wrapping too tight — restricting follower's movement", "Follower resisting the wrap", "Getting tangled in the unwrap", "Not maintaining slot integrity"]),
  },
  {
    name: "Reverse Whip",
    slug: "reverse-whip",
    beats: 8,
    difficulty: "intermediate",
    category: "push-pull",
    description: "The whip pattern done in reverse — follower starts moving away and is drawn back in.",
    mechanics: JSON.stringify(["1-2: Leader sends follower away", "3&4: Leader draws follower back with stretch", "5-6: Follower returns toward leader", "7&8: Both anchor after the return"]),
    commonMistakes: JSON.stringify(["Not creating enough initial stretch on 1-2", "Follower not responding to the draw on 3&4", "Losing the slot during the reverse movement", "Missing the anchor timing"]),
  },
  {
    name: "Side Pass with Hook",
    slug: "side-pass-with-hook",
    beats: 6,
    difficulty: "intermediate",
    category: "push-pull",
    description: "A side pass where follower hooks (half turn) at the end before anchoring.",
    mechanics: JSON.stringify(["1-2: Leader initiates side pass", "3&4: Follower walks through the slot", "4-5: Leader leads a hook (half rotation) at the end", "5&6: Follower finishes facing leader, both anchor"]),
    commonMistakes: JSON.stringify(["Leader leading the hook too early", "Follower anticipating the hook", "Hook rotation being too big — should be about 180 degrees", "Losing connection after the hook"]),
  },
  {
    name: "Yo-Yo",
    slug: "yo-yo",
    beats: 6,
    difficulty: "intermediate",
    category: "push-pull",
    description: "Quick compression-extension pattern. Follower bounces between leader and end of slot.",
    mechanics: JSON.stringify(["1: Sharp compression toward leader", "2: Quick redirect outward", "3&4: Follower extends to end of slot", "5&6: Both anchor at maximum stretch"]),
    commonMistakes: JSON.stringify(["Making it too aggressive", "Follower not matching the leader's energy", "Losing the slot during rapid direction changes", "Not finding the music in the movement"]),
  },
  {
    name: "Sweetheart",
    slug: "sweetheart",
    beats: 8,
    difficulty: "intermediate",
    category: "push-pull",
    description: "Both partners end up side by side, follower tucked under leader's arm in sweetheart position.",
    mechanics: JSON.stringify(["1-2: Leader opens to allow follower in", "3&4: Follower turns into sweetheart position (side by side)", "5-6: Both walk together in sweetheart hold", "7&8: Leader unwinds follower, both anchor"]),
    commonMistakes: JSON.stringify(["Arm position too tight in sweetheart hold", "Not walking together smoothly", "Messy entry or exit from the position", "Losing timing while in side-by-side"]),
  },
  {
    name: "Texas Tommy",
    slug: "texas-tommy",
    beats: 8,
    difficulty: "advanced",
    category: "push-pull",
    description: "Hand passes behind follower's back, creating a dramatic wrap-unwrap through the slot.",
    mechanics: JSON.stringify(["1-2: Follower walks toward leader", "3&4: Leader passes follower's hand behind their back", "5-6: Follower walks down slot with hand behind back", "7&8: Leader unwraps, both anchor"]),
    commonMistakes: JSON.stringify(["Not passing the hand smoothly behind back", "Follower tensing up during the hand pass", "Leader holding on too tight", "Awkward unwrap — should feel effortless"]),
  },

  // === TURNS (10) ===
  {
    name: "Outside Turn",
    slug: "outside-turn",
    beats: 6,
    difficulty: "beginner",
    category: "turns",
    description: "Follower turns away from the lead arm. Creates space and looks elegant.",
    mechanics: JSON.stringify(["1: Leader preps by stepping back", "2: Leader initiates outward rotation", "3&4: Follower executes outside turn through the slot", "5&6: Both anchor — reconnect with stretch"]),
    commonMistakes: JSON.stringify(["Follower not spotting during the turn", "Leader pulling instead of guiding", "Turn not traveling down the slot", "Wobbly anchor after the turn"]),
  },
  {
    name: "Inside Turn",
    slug: "inside-turn",
    beats: 6,
    difficulty: "beginner",
    category: "turns",
    description: "Follower turns toward the lead arm. Complementary to the outside turn.",
    mechanics: JSON.stringify(["1: Leader preps by stepping back", "2: Leader initiates inward rotation", "3&4: Follower executes inside turn through slot", "5&6: Both anchor with reconnection"]),
    commonMistakes: JSON.stringify(["Over-rotating — turning past the partner", "Not maintaining upward posture during turn", "Leader cranking the arm for rotation", "Disconnected anchor"]),
  },
  {
    name: "Double Turn",
    slug: "double-turn",
    beats: 6,
    difficulty: "intermediate",
    category: "turns",
    description: "Two full rotations in the space of one pattern. Requires good balance and spotting.",
    mechanics: JSON.stringify(["1: Leader creates strong rotational prep", "2: Leader gives rotational energy for two turns", "3&4: Follower executes two full rotations", "5&6: Both anchor — follower catches balance"]),
    commonMistakes: JSON.stringify(["Not enough rotational energy for two turns", "Follower losing balance mid-turn", "Not spotting — dizziness", "Leader over-leading causing a third rotation"]),
  },
  {
    name: "Free Spin",
    slug: "free-spin",
    beats: 6,
    difficulty: "intermediate",
    category: "turns",
    description: "Leader releases follower for a free (unconnected) spin. Tests follower's independent balance.",
    mechanics: JSON.stringify(["1-2: Build compression together", "3: Leader releases, follower initiates own spin", "4: Follower completes spin independently", "5&6: Reconnect and anchor"]),
    commonMistakes: JSON.stringify(["Follower depending on leader for spin momentum", "Leader not releasing cleanly", "Follower traveling during the free spin", "Late reconnection — missing the anchor"]),
  },
  {
    name: "Hammerlock Turn",
    slug: "hammerlock-turn",
    beats: 6,
    difficulty: "intermediate",
    category: "turns",
    description: "Turn that results in follower's arm behind their back (hammerlock position).",
    mechanics: JSON.stringify(["1: Leader redirects follower", "2: Lead for inside turn", "3&4: Follower turns, arm ends up behind back in hammerlock", "5&6: Both anchor in hammerlock position"]),
    commonMistakes: JSON.stringify(["Forcing the arm position — should happen naturally from the turn", "Hammerlock too tight — uncomfortable for follower", "Not knowing how to exit the hammerlock smoothly", "Follower pre-locking the arm"]),
  },
  {
    name: "Spin to Hammerlock",
    slug: "spin-to-hammerlock",
    beats: 8,
    difficulty: "advanced",
    category: "turns",
    description: "Free spin that finishes in a hammerlock. Combines independence with partner connection.",
    mechanics: JSON.stringify(["1-2: Build energy for the spin", "3&4: Follower free spins", "5: Leader catches into hammerlock", "6: Settle into position", "7&8: Anchor in hammerlock"]),
    commonMistakes: JSON.stringify(["Catching too aggressively", "Follower not finishing spin in catchable position", "Timing mismatch on the catch", "Uncomfortable arm position"]),
  },
  {
    name: "Rolling Off the Arm",
    slug: "rolling-off-the-arm",
    beats: 6,
    difficulty: "intermediate",
    category: "turns",
    description: "Follower rolls across leader's arm for a smooth, connected rotation through the slot.",
    mechanics: JSON.stringify(["1-2: Set up with arm positioned for the roll", "3: Follower begins rolling across leader's arm", "4: Complete the roll", "5&6: Both anchor — reconnect"]),
    commonMistakes: JSON.stringify(["Leader's arm too rigid — should be a soft guide", "Follower grabbing the arm instead of rolling across", "Not maintaining slot during the roll", "Losing frame"]),
  },
  {
    name: "Leader Turn",
    slug: "leader-turn",
    beats: 6,
    difficulty: "intermediate",
    category: "turns",
    description: "Leader turns instead of (or in addition to) the follower. Adds variety and surprise.",
    mechanics: JSON.stringify(["1: Leader initiates own turn", "2: Leader rotates while maintaining connection", "3&4: Leader completes turn, both triple step", "5&6: Both anchor"]),
    commonMistakes: JSON.stringify(["Losing connection with follower during leader's turn", "Follower not knowing what to do when leader turns", "Leader getting dizzy", "Not maintaining slot"]),
  },
  {
    name: "Continuous Turns",
    slug: "continuous-turns",
    beats: 8,
    difficulty: "advanced",
    category: "turns",
    description: "Multiple turns strung together across an 8-count. Requires excellent spotting and balance.",
    mechanics: JSON.stringify(["1-2: First turn with maintained connection", "3&4: Continue turning — second rotation", "5-6: Third turn or variation", "7&8: Final turn into anchor"]),
    commonMistakes: JSON.stringify(["Running out of steam mid-sequence", "Progressive loss of balance", "Not breathing during turns", "Forgetting to anchor at the end"]),
  },
  {
    name: "Paddle Turn",
    slug: "paddle-turn",
    beats: 8,
    difficulty: "intermediate",
    category: "turns",
    description: "Series of small turns in place, led step-by-step. Used for musical interpretation.",
    mechanics: JSON.stringify(["1: Small rotation (quarter turn)", "2: Another quarter turn", "3&4: Continue paddle turning", "5-6: Keep paddle turning to fill the music", "7&8: Settle and anchor"]),
    commonMistakes: JSON.stringify(["Making paddle turns too big", "Losing rhythm — each step should be on a beat", "Not matching the music's energy", "Getting off balance from the repeated rotations"]),
  },

  // === WHIPS (10) ===
  {
    name: "Whip with Inside Turn",
    slug: "whip-inside-turn",
    beats: 8,
    difficulty: "intermediate",
    category: "whips",
    description: "Standard whip with an inside turn at the redirection point. Adds flair to the basic whip.",
    mechanics: JSON.stringify(["1-2: Follower walks toward leader", "3&4: Leader redirects into inside turn", "5-6: Follower walks back down slot", "7&8: Both anchor"]),
    commonMistakes: JSON.stringify(["Turn too early — should happen at the redirection", "Losing the whip structure for the turn", "Not traveling back down the slot after the turn", "Missing the anchor"]),
  },
  {
    name: "Whip with Outside Turn",
    slug: "whip-outside-turn",
    beats: 8,
    difficulty: "intermediate",
    category: "whips",
    description: "Standard whip with an outside turn at the redirection. Looks smooth and open.",
    mechanics: JSON.stringify(["1-2: Follower walks toward leader", "3&4: Leader redirects into outside turn", "5-6: Follower walks back", "7&8: Both anchor"]),
    commonMistakes: JSON.stringify(["Leader not creating enough room for outside turn", "Follower not spotting", "Turn happening at the wrong count", "Losing connection during the turn"]),
  },
  {
    name: "Whip with Free Spin",
    slug: "whip-free-spin",
    beats: 8,
    difficulty: "advanced",
    category: "whips",
    description: "Whip where leader releases follower for a free spin at the redirection point.",
    mechanics: JSON.stringify(["1-2: Follower walks in", "3: Leader releases with rotational energy", "&4: Follower free spins", "5-6: Reconnect, walk back", "7&8: Anchor"]),
    commonMistakes: JSON.stringify(["Release timing off", "Not enough energy for the free spin", "Follower not reconnecting in time for walk back", "Sloppy anchor"]),
  },
  {
    name: "Throw Out Whip",
    slug: "throw-out-whip",
    beats: 8,
    difficulty: "intermediate",
    category: "whips",
    description: "At the redirection, leader throws follower outward with more energy than a standard whip.",
    mechanics: JSON.stringify(["1-2: Follower walks toward leader", "3&4: Strong redirection — leader throws follower out", "5-6: Follower travels to end of slot with momentum", "7&8: Both anchor with stretch"]),
    commonMistakes: JSON.stringify(["Too much force — should be led, not thrown", "Follower not managing the momentum", "Not maintaining the slot", "Anchor too disconnected"]),
  },
  {
    name: "Sliding Door Whip",
    slug: "sliding-door-whip",
    beats: 8,
    difficulty: "advanced",
    category: "whips",
    description: "Leader and follower pass each other like sliding doors during the whip pattern.",
    mechanics: JSON.stringify(["1-2: Follower and leader walk toward each other", "3&4: Both pass each other, switching sides", "5-6: Both continue to opposite ends", "7&8: Both anchor at swapped positions"]),
    commonMistakes: JSON.stringify(["Collision risk — both need to commit to their path", "Timing mismatch on the pass", "Not clearing enough space", "Losing orientation after the pass"]),
  },
  {
    name: "Whip with Body Roll",
    slug: "whip-body-roll",
    beats: 8,
    difficulty: "advanced",
    category: "whips",
    description: "Whip pattern with a body roll at the redirection. Musical and visually striking.",
    mechanics: JSON.stringify(["1-2: Follower walks in", "3&4: Body roll at the redirection point", "5-6: Walk back down the slot", "7&8: Anchor"]),
    commonMistakes: JSON.stringify(["Body roll too stiff — needs to be fluid", "Body roll takes too long, throwing off timing", "Not integrated with the whip — looks separate", "Losing connection during the roll"]),
  },
  {
    name: "Whip with Hesitation",
    slug: "whip-hesitation",
    beats: 8,
    difficulty: "intermediate",
    category: "whips",
    description: "Whip with a deliberate pause/hesitation at the top. Great for musical breaks.",
    mechanics: JSON.stringify(["1-2: Follower walks in", "3: Hesitation — both pause", "&4: Resume with redirection", "5-6: Walk back", "7&8: Anchor"]),
    commonMistakes: JSON.stringify(["Hesitation too long or too short", "Not matching the hesitation to the music", "Follower not responsive to the pause", "Resuming too abruptly"]),
  },
  {
    name: "Apache Whip",
    slug: "apache-whip",
    beats: 8,
    difficulty: "advanced",
    category: "whips",
    description: "Dramatic whip with a dip or lean at the redirection point. Show-stopping when done well.",
    mechanics: JSON.stringify(["1-2: Follower walks in with energy", "3: Leader catches and dips/leans", "&4: Recover from the dip", "5-6: Walk back to end of slot", "7&8: Anchor"]),
    commonMistakes: JSON.stringify(["Dip too deep — unsafe", "Not supporting follower properly during the dip", "Follower not trusting the leader's support", "Recovery too slow, throwing off timing"]),
  },
  {
    name: "Pretzel Whip",
    slug: "pretzel-whip",
    beats: 8,
    difficulty: "advanced",
    category: "whips",
    description: "Whip with crossed-arm (pretzel) hold through the redirection. Creates intricate arm work.",
    mechanics: JSON.stringify(["1-2: Follower walks in", "3&4: Cross arms at the redirection", "5-6: Walk back in crossed position", "7&8: Unwind and anchor"]),
    commonMistakes: JSON.stringify(["Arms getting tangled", "Not comfortable in the crossed position", "Unwind direction wrong", "Too much tension in the arms"]),
  },
  {
    name: "Window Whip",
    slug: "window-whip",
    beats: 8,
    difficulty: "intermediate",
    category: "whips",
    description: "Whip where leader creates a 'window' frame with arms for follower to duck through.",
    mechanics: JSON.stringify(["1-2: Follower walks toward leader", "3&4: Leader raises arms creating window, follower ducks through", "5-6: Follower exits on other side", "7&8: Both anchor"]),
    commonMistakes: JSON.stringify(["Window too small — follower can't pass through", "Follower ducking too dramatically", "Leader dropping the window too early", "Losing slot orientation"]),
  },

  // === WRAPS (10) ===
  {
    name: "Basic Wrap",
    slug: "basic-wrap",
    beats: 6,
    difficulty: "intermediate",
    category: "wraps",
    description: "Leader wraps follower's arm around their own body. Foundation for wrap variations.",
    mechanics: JSON.stringify(["1: Leader starts the wrap motion", "2: Follower's arm crosses over body", "3&4: Settle into wrapped position", "5&6: Unwrap and anchor"]),
    commonMistakes: JSON.stringify(["Wrapping too tightly", "Not smooth transition into the wrap", "Follower fighting the wrap", "Messy unwrap"]),
  },
  {
    name: "Self Wrap",
    slug: "self-wrap",
    beats: 6,
    difficulty: "intermediate",
    category: "wraps",
    description: "Leader wraps themselves instead of the follower. Unexpected and fun.",
    mechanics: JSON.stringify(["1: Leader initiates self-wrap", "2: Leader crosses arm across own body", "3&4: Leader turns into the wrap", "5&6: Unwrap and anchor"]),
    commonMistakes: JSON.stringify(["Getting tangled in own wrap", "Losing connection with follower", "Follower confused about what to do", "Not unwinding smoothly"]),
  },
  {
    name: "Double Wrap",
    slug: "double-wrap",
    beats: 8,
    difficulty: "advanced",
    category: "wraps",
    description: "Two wrap layers — creates a more dramatic look and requires precise unwinding.",
    mechanics: JSON.stringify(["1-2: First wrap layer", "3&4: Second wrap layer", "5-6: Begin unwrap", "7&8: Complete unwrap, anchor"]),
    commonMistakes: JSON.stringify(["Getting lost in which direction to unwrap", "Wrapping too tight to unwind", "Arms crossing uncomfortably", "Panic — forgetting the exit"]),
  },
  {
    name: "Wrap Turn",
    slug: "wrap-turn",
    beats: 8,
    difficulty: "intermediate",
    category: "wraps",
    description: "A wrap that transitions into a turn for the unwinding. Combines two techniques.",
    mechanics: JSON.stringify(["1-2: Leader initiates wrap", "3&4: Follower turns into the wrap", "5-6: Continue turning to unwrap", "7&8: Exit cleanly, anchor"]),
    commonMistakes: JSON.stringify(["Turn direction wrong — wrapping tighter instead of unwrapping", "Not enough turn for a clean exit", "Lost count during the wrap-turn", "Connection break"]),
  },
  {
    name: "Neck Wrap",
    slug: "neck-wrap",
    beats: 8,
    difficulty: "advanced",
    category: "wraps",
    description: "Follower's arm drapes around leader's neck. Intimate styling that requires trust.",
    mechanics: JSON.stringify(["1-2: Leader guides follower's arm up", "3&4: Arm drapes around leader's neck/shoulder", "5-6: Walk together in close position", "7&8: Exit the wrap, anchor"]),
    commonMistakes: JSON.stringify(["Arm actually choking leader — should drape, not grip", "Moving too fast into the position", "Follower's hand landing on leader's face", "Not comfortable enough with partner for this move"]),
  },
  {
    name: "Waist Wrap",
    slug: "waist-wrap",
    beats: 6,
    difficulty: "intermediate",
    category: "wraps",
    description: "Follower wraps around leader's waist or vice versa. Creates close body connection.",
    mechanics: JSON.stringify(["1: Begin guiding follower into waist wrap", "2: Follower's arm wraps around leader's waist", "3&4: Brief moment in close position", "5&6: Unwrap and anchor"]),
    commonMistakes: JSON.stringify(["Too grabby — should be a smooth guide", "Follower ending up off-balance in the wrap", "Not enough space to breathe in the position", "Awkward unwrap"]),
  },
  {
    name: "Back Wrap",
    slug: "back-wrap",
    beats: 8,
    difficulty: "advanced",
    category: "wraps",
    description: "Follower wraps behind leader's back. Creates an interesting visual line.",
    mechanics: JSON.stringify(["1-2: Leader turns to allow follower behind", "3&4: Follower wraps behind leader's back", "5-6: Both in wrapped position", "7&8: Unwrap with turn, anchor"]),
    commonMistakes: JSON.stringify(["Follower can't see — needs to trust the lead", "Leader turning too fast", "Getting stuck in the position", "Not planned exit strategy"]),
  },
  {
    name: "Cuddle Wrap",
    slug: "cuddle-wrap",
    beats: 6,
    difficulty: "intermediate",
    category: "wraps",
    description: "Similar to sweetheart but both arms wrap. Creates a cozy side-by-side position.",
    mechanics: JSON.stringify(["1: Begin turning follower into cuddle", "2: Both arms cross into cuddle position", "3&4: Walk together in cuddle hold", "5&6: Unwind and anchor"]),
    commonMistakes: JSON.stringify(["Arms twisted uncomfortably", "Not traveling together smoothly", "Unwind direction confusion", "Too much tension in the hold"]),
  },
  {
    name: "Pretzel Wrap",
    slug: "pretzel-wrap",
    beats: 8,
    difficulty: "advanced",
    category: "wraps",
    description: "Complex arm interweaving that looks complicated but unwinds cleanly with the right technique.",
    mechanics: JSON.stringify(["1-2: First cross — right over left (or vice versa)", "3&4: Second cross — creating the pretzel", "5-6: Begin unwinding", "7&8: Complete the unwind, anchor"]),
    commonMistakes: JSON.stringify(["Wrong cross direction — leads to a knot", "Arms too tense to unwind", "Forgetting the unwind sequence", "Follower panicking in the pretzel"]),
  },
  {
    name: "Shadow Wrap",
    slug: "shadow-wrap",
    beats: 8,
    difficulty: "intermediate",
    category: "wraps",
    description: "Follower ends up behind leader in shadow position through a wrap movement.",
    mechanics: JSON.stringify(["1-2: Leader draws follower around", "3&4: Follower moves behind leader into shadow position", "5-6: Both move together in shadow hold", "7&8: Follower exits shadow, anchor"]),
    commonMistakes: JSON.stringify(["Follower can't see where they're going", "Leader forgetting follower is behind them", "Entry into shadow too rough", "Exit not clean"]),
  },

  // === SLIDES (10) ===
  {
    name: "Basic Slide",
    slug: "basic-slide",
    beats: 6,
    difficulty: "beginner",
    category: "slides",
    description: "Follower slides through the slot with a smooth, gliding step. Emphasis on floor contact.",
    mechanics: JSON.stringify(["1: Leader opens the slot", "2: Follower begins sliding through", "3&4: Long smooth slide through the slot", "5&6: Settle and anchor"]),
    commonMistakes: JSON.stringify(["Picking feet up instead of sliding", "Not maintaining connection during the slide", "Floor surface not smooth enough for sliding", "Losing balance during the glide"]),
  },
  {
    name: "Sliding Door",
    slug: "sliding-door",
    beats: 8,
    difficulty: "intermediate",
    category: "slides",
    description: "Both partners slide past each other in the slot, like sliding doors. Requires timing sync.",
    mechanics: JSON.stringify(["1-2: Both begin moving toward each other", "3&4: Both slide past each other — slight body rotation", "5-6: Continue to opposite ends", "7&8: Both anchor at new positions"]),
    commonMistakes: JSON.stringify(["Not enough space — collision", "Timing mismatch on the pass", "One person sliding, other walking", "Not maintaining the slot"]),
  },
  {
    name: "Sailor Shuffle",
    slug: "sailor-shuffle",
    beats: 6,
    difficulty: "intermediate",
    category: "slides",
    description: "Cross-behind step pattern that creates a bouncy, sailing motion. Great for upbeat music.",
    mechanics: JSON.stringify(["1: Cross right behind left (or vice versa)", "2: Step side", "3&4: Sailor shuffle triple", "5&6: Anchor with the sailor feel"]),
    commonMistakes: JSON.stringify(["Cross too big — losing balance", "Not maintaining the bouncy quality", "Losing the slot", "Not matching the music's bounce"]),
  },
  {
    name: "Kick Slide",
    slug: "kick-slide",
    beats: 6,
    difficulty: "intermediate",
    category: "slides",
    description: "A kick followed by a slide through the slot. Adds sharp dynamics to movement.",
    mechanics: JSON.stringify(["1: Small kick forward", "2: Land from kick", "3&4: Slide through the slot", "5&6: Settle and anchor"]),
    commonMistakes: JSON.stringify(["Kick too high — should be small and controlled", "Not connecting kick momentum to the slide", "Losing balance on the kick", "Kick in wrong direction"]),
  },
  {
    name: "Glide and Turn",
    slug: "glide-and-turn",
    beats: 8,
    difficulty: "intermediate",
    category: "slides",
    description: "Long glide through the slot that transitions into a turn at the end.",
    mechanics: JSON.stringify(["1-2: Begin long glide through the slot", "3&4: Continue gliding — build momentum", "5: Begin turn from glide energy", "6: Complete turn", "7&8: Anchor"]),
    commonMistakes: JSON.stringify(["Glide not smooth — choppy", "Not enough momentum for the turn", "Turn off-balance from the glide", "Not maintaining the slot"]),
  },
  {
    name: "Body Slide",
    slug: "body-slide",
    beats: 8,
    difficulty: "advanced",
    category: "slides",
    description: "Full body contact slide where one partner slides along the other's body. Advanced styling.",
    mechanics: JSON.stringify(["1-2: Close position, begin the body slide", "3&4: Slide along partner's body with control", "5-6: Complete the slide, create separation", "7&8: Anchor with stretch"]),
    commonMistakes: JSON.stringify(["Too much contact — should be controlled", "Not appropriate for social dancing with strangers", "Losing balance during the slide", "Not enough trust between partners"]),
  },
  {
    name: "Toe Slide",
    slug: "toe-slide",
    beats: 6,
    difficulty: "intermediate",
    category: "slides",
    description: "Sliding on the ball of the foot / toes for a precise, elegant movement through the slot.",
    mechanics: JSON.stringify(["1: Rise to toes", "2: Begin toe slide through slot", "3&4: Continue sliding on toes", "5&6: Lower and anchor"]),
    commonMistakes: JSON.stringify(["Rising too high — not stable", "Shoe grip preventing smooth slide", "Not maintaining elegant posture during slide", "Landing hard out of the slide"]),
  },
  {
    name: "Cross Body Slide",
    slug: "cross-body-slide",
    beats: 8,
    difficulty: "advanced",
    category: "slides",
    description: "Follower slides across the body line (perpendicular to slot) for a dramatic moment.",
    mechanics: JSON.stringify(["1-2: Set up perpendicular to slot", "3&4: Follower slides across the body line", "5-6: Return to slot orientation", "7&8: Anchor"]),
    commonMistakes: JSON.stringify(["Going too far off the slot", "Not maintaining connection during perpendicular movement", "Floor conditions not suitable", "Not returning to slot cleanly"]),
  },
  {
    name: "Moonwalk Slide",
    slug: "moonwalk-slide",
    beats: 8,
    difficulty: "advanced",
    category: "slides",
    description: "Backward sliding movement inspired by the moonwalk. Fun styling for musical accents.",
    mechanics: JSON.stringify(["1-2: Set up for backward movement", "3&4: Execute moonwalk-style backward slide", "5-6: Continue or transition forward", "7&8: Anchor"]),
    commonMistakes: JSON.stringify(["Not actually sliding — just walking backward", "Losing connection with partner", "Off-balance during backward movement", "Not matching the musical moment"]),
  },
  {
    name: "Drag Slide",
    slug: "drag-slide",
    beats: 6,
    difficulty: "intermediate",
    category: "slides",
    description: "One foot drags along the floor while the other steps. Creates a grounded, bluesy feel.",
    mechanics: JSON.stringify(["1: Step with one foot", "2: Drag the other foot to meet it", "3&4: Step and drag through the slot", "5&6: Anchor with drag feel"]),
    commonMistakes: JSON.stringify(["Drag too fast — should be deliberate", "Not enough weight on the dragging foot", "Losing the grounded quality", "Not musical — drag should match the music's feel"]),
  },
];

const anchors = [
  {
    name: "Standard Anchor",
    slug: "standard-anchor",
    description: "The fundamental anchor step. Triple step in place with stretch and compression creating an elastic connection with your partner.",
    execution: JSON.stringify(["Beat 5: Step back with right foot (follower) or left foot (leader), creating stretch", "Beat &: Close with opposite foot", "Beat 6: Step in place, settling into the connection", "Maintain resistance — don't collapse toward partner", "Arms should have tone but not rigidity"]),
    musicality: "Use for everything — it's the default. Works with any tempo or mood. The bread and butter of WCS.",
    difficulty: "beginner",
  },
  {
    name: "Sailing Anchor",
    slug: "sailing-anchor",
    description: "Smooth, elongated anchor that glides through the beats. Like sailing through water — no sharp stops.",
    execution: JSON.stringify(["Beat 5: Begin long step back with smooth transfer", "Beat &: Glide through — no sharp step, just flow", "Beat 6: Complete the smooth weight transfer", "Everything is legato — connected and flowing", "Think of pulling taffy — slow, smooth, continuous"]),
    musicality: "Perfect for slow, smooth songs. R&B, ballads, or any music with sustained notes and long phrases.",
    difficulty: "intermediate",
  },
  {
    name: "Stutter Anchor",
    slug: "stutter-anchor",
    description: "Quick, choppy anchor with extra steps squeezed in. Adds rhythmic interest and energy to the end of a pattern.",
    execution: JSON.stringify(["Beat 5: Quick step back", "Beat &: Quick step (extra stutter)", "Beat a: Another quick step (the stutter)", "Beat 6: Final step — grounding", "Keep it small — the extra steps are in place, not traveling", "Stay grounded — the energy is rhythmic, not vertical"]),
    musicality: "Best for uptempo songs with lots of rhythmic detail. Funk, pop, or when the music has staccato elements.",
    difficulty: "intermediate",
  },
  {
    name: "Syncopated Anchor",
    slug: "syncopated-anchor",
    description: "Plays with off-beat timing for the anchor steps. Creates rhythmic tension that resolves satisfyingly.",
    execution: JSON.stringify(["Break the standard timing — delay or anticipate steps", "Beat 5: Hold or delay the first step", "Beat &: Sharp step on the off-beat", "Beat 6: Resolve into the ground", "The key is intentional timing shifts, not being late", "Must be musical — the syncopation should match the music"]),
    musicality: "For music with syncopated rhythms, jazz elements, or when you hear something interesting in the off-beats.",
    difficulty: "advanced",
  },
  {
    name: "Body Roll Anchor",
    slug: "body-roll-anchor",
    description: "Replace the triple step with a body roll that flows from chest to hips. Dramatic and sensual styling.",
    execution: JSON.stringify(["Beat 5: Initiate roll from chest", "Beat &: Roll passes through torso", "Beat 6: Complete roll through hips, grounding into the floor", "Keep feet planted — the movement is in the body", "Arms maintain connection while body rolls", "Don't force it — it should flow naturally"]),
    musicality: "Perfect for slow, sultry music. R&B, blues, or any music with a strong groove. Use on dramatic moments.",
    difficulty: "advanced",
  },
  {
    name: "Musical Anchor",
    slug: "musical-anchor",
    description: "Freestyle anchor that responds directly to what you hear in the music. No fixed footwork — pure interpretation.",
    execution: JSON.stringify(["Listen to the music — what does it call for?", "Match your movement to the specific sounds you hear", "Could be a hit, a slide, a pause, a roll — anything", "Maintain connection and stretch with partner", "Stay grounded — don't lose the anchor function", "The goal is to make the music visible through your body"]),
    musicality: "For any music — this is about listening and responding. Best used when you really know a song or feel a strong musical impulse.",
    difficulty: "advanced",
  },
];

const checklistTemplates = [
  // Connection (3 items)
  { category: "connection", item: "Maintain consistent frame tension throughout the pattern", sortOrder: 1 },
  { category: "connection", item: "Match partner's energy — don't overpower or go limp", sortOrder: 2 },
  { category: "connection", item: "Smooth hand transitions — no grabbing or dropping", sortOrder: 3 },
  // Frame (3 items)
  { category: "frame", item: "Elbows stay in front of body, never behind", sortOrder: 4 },
  { category: "frame", item: "Shoulders down and relaxed, not hunched", sortOrder: 5 },
  { category: "frame", item: "Wrists neutral — not broken or overly rigid", sortOrder: 6 },
  // Posture (3 items)
  { category: "posture", item: "Weight forward over balls of feet, not on heels", sortOrder: 7 },
  { category: "posture", item: "Core engaged — stable center of gravity", sortOrder: 8 },
  { category: "posture", item: "Head up, eyes forward — not looking at feet", sortOrder: 9 },
  // Timing (4 items)
  { category: "timing", item: "Triple steps are evenly spaced (not galloping)", sortOrder: 10 },
  { category: "timing", item: "Walk steps hit clearly on the beat", sortOrder: 11 },
  { category: "timing", item: "Anchor completes before next pattern begins", sortOrder: 12 },
  { category: "timing", item: "Rhythm matches the music, not just counting", sortOrder: 13 },
  // Styling (3 items)
  { category: "styling", item: "Body moves with the music — not robotic", sortOrder: 14 },
  { category: "styling", item: "Free hand has intentional placement", sortOrder: 15 },
  { category: "styling", item: "Smooth transitions between patterns — no jerky movements", sortOrder: 16 },
];

async function main() {
  console.log("Seeding database...");

  // Seed patterns
  for (const p of patterns) {
    await prisma.pattern.upsert({
      where: { slug: p.slug },
      update: p,
      create: p,
    });
  }
  console.log(`Seeded ${patterns.length} patterns`);

  // Seed anchor types
  for (const a of anchors) {
    await prisma.anchorType.upsert({
      where: { slug: a.slug },
      update: a,
      create: a,
    });
  }
  console.log(`Seeded ${anchors.length} anchor types`);

  // Seed checklist templates for each pattern
  const allPatterns = await prisma.pattern.findMany();
  let checklistCount = 0;
  for (const pattern of allPatterns) {
    for (const tmpl of checklistTemplates) {
      const existing = await prisma.checklistTemplate.findFirst({
        where: {
          patternId: pattern.id,
          category: tmpl.category,
          item: tmpl.item,
        },
      });
      if (!existing) {
        await prisma.checklistTemplate.create({
          data: {
            patternId: pattern.id,
            ...tmpl,
          },
        });
        checklistCount++;
      }
    }
  }
  console.log(`Seeded ${checklistCount} checklist templates`);

  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
